apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../cc.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: broker
  name: broker
spec:
  clusterIP: "None"
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "29092"
      port: 29092
      targetPort: 29092
    - name: "29093"
      port: 29093
      targetPort: 29093
  selector:
    io.kompose.service: broker
