apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../cc.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: calculator
  name: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: calculator
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../cc.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: calculator
    spec:
      containers:
        - env:
            - name: GRPC_DNS_RESOLVER
              value: native
            - name: MONGO_URI
              value: mongodb://<REPLACE>:<REPLACE>@mongo:27017
          image: distributed-systems-2025-calculator
          name: calculator
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50052
              protocol: TCP
      restartPolicy: Always
