apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../cc.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: locust
  name: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: locust
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../cc.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: locust
    spec:
      containers:
        - args:
            - -f
            - /mnt/locust/load_tests.py
          image: docker.io/locustio/locust
          name: locust
          ports:
            - containerPort: 8089
              protocol: TCP
      restartPolicy: Always
