apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../cc.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: locust-metrics-exporter
  name: locust-metrics-exporter
spec:
  ports:
    - name: "9646"
      port: 9646
      targetPort: 9646
  selector:
    io.kompose.service: locust-metrics-exporter
