apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../cc.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: pyspy
  name: pyspy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pyspy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../cc.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: pyspy
    spec:
      containers:
        - image: localhost/distributed-systems-2025_pyspy
          name: pyspy
          securityContext:
            privileged: true
      restartPolicy: Always
